# filename: pvc.yaml
# author: Christian Blank (https://github.com/Cyneric)
# created date: 2024-11-08
# description: PersistentVolumeClaim for the application

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: addarr-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: '{{ .Values.storageClassName }}'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
